name: shamo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cloud_firestore: ^5.6.12
  dio: ^5.8.0+1
  firebase_core: ^3.15.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  http: ^1.4.0
  jiffy: ^6.4.3
  provider: ^6.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "android/app/src/main/ic_launcher-playstore.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#1F1D2B"
  macos:
    generate: true
    image_path: "android/app/src/main/ic_launcher-playstore.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
