// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK3d814_J1AT3YU6yg4cQYzkLMo-xmFZw',
    appId: '1:888741578846:android:cd1eb5fd669ebd08084ccf',
    messagingSenderId: '888741578846',
    projectId: 'taufiq-shamo',
    storageBucket: 'taufiq-shamo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5ADMOyC1hyJEEM3uFxuT5yD2EPftUkpU',
    appId: '1:888741578846:ios:b278187e20a5b23b084ccf',
    messagingSenderId: '888741578846',
    projectId: 'taufiq-shamo',
    storageBucket: 'taufiq-shamo.firebasestorage.app',
    iosBundleId: 'com.taufiqsejati.shamo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5ADMOyC1hyJEEM3uFxuT5yD2EPftUkpU',
    appId: '1:888741578846:ios:b278187e20a5b23b084ccf',
    messagingSenderId: '888741578846',
    projectId: 'taufiq-shamo',
    storageBucket: 'taufiq-shamo.firebasestorage.app',
    iosBundleId: 'com.taufiqsejati.shamo',
  );
}
